-- Migration 029: [DESATIVADA — INCIDENTE 20/07/2026]
--
-- A versão original desta migration agendava sync Shopee para CADA hora do dia
-- (24 jobs). Aplicada às ~18:45 BRT de 20/07, derrubou o banco compartilhado
-- (produção + hml): o disparo de hora cheia somado às retry chains de tasks
-- vazias (12 retries/hora por usuário sem vendas) saturou o Postgres —
-- login travado, 401 em cascata (usuários deslogados), dashboard 1min+.
--
-- Mitigação aplicada manualmente às ~19:50 BRT:
--   - restart do projeto Supabase
--   - unschedule dos 19 jobs horários
--   - cronograma restaurado: 7h, 9h, 10h, 11h, 12h BRT (incremental) + 01h BRT (full)
--
-- O sync horário será reintroduzido na migration 030 SOMENTE após o deploy do
-- fix "sem retry chain em sync incremental" (app/tasks/shopee_tasks.py) no
-- backend que o pg_cron chama (Vault backend_base_url = api.hml.marketdash.com.br).
--
-- Esta migration agora é um NO-OP proposital.
SELECT 1;
